DevOps for Developers/Software Engineering and DevOps - Sep 2024/08. Exams/SEDO-Regular-Exam-2024-10/HouseRentingSystem.Web/Models/Home/IndexViewModel.cs
namespace HouseRentingSystem.Web.Models.Home
{
    public class IndexViewModel
    {

    }
}

DevOps for Developers/Software Engineering and DevOps - Sep 2024/08. Exams/SEDO-Regular-Exam-2024-10/HouseRentingSystem.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Web.Areas.Admin.Controllers
{
    public class HomeController 
        : AdminController
    {
        public IActionResult Index()
            => View();
    }
}

DevOps for Developers/Software Engineering and DevOps - Sep 2024/08. Exams/SEDO-Regular-Exam-2024-10/HouseRentingSystem.Web/Areas/Admin/Controllers/HousesController.cs
using HouseRentingSystem.Services.Agents;
using HouseRentingSystem.Services.Houses;
using HouseRentingSystem.Web.Areas.Admin.Models;
using HouseRentingSystem.Web.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Web.Areas.Admin.Controllers
{
    public class HousesController : AdminController
    {
        private readonly IHouseService houses;
        private readonly IAgentService agents;

        public HousesController(IHouseService houses,
            IAgentService agents)
        {
            this.houses = houses;
            this.agents = agents;
        }

        public IActionResult Mine()
        {
            var myHouses = new MyHousesViewModel();

            var adminUserId = this.User.Id();
            myHouses.RentedHouses = this.houses.AllHousesByUserId(adminUserId);

            var adminAgentId = this.agents.GetAgentId(adminUserId);
            myHouses.AddedHouses = this.houses.AllHousesByAgentId(adminAgentId);

            return View(myHouses);
        }
    }
}

DevOps for Developers/Software Engineering and DevOps - Sep 2024/08. Exams/SEDO-Regular-Exam-2024-10/HouseRentingSystem.Web/Controllers/HomeController.cs
using HouseRentingSystem.Web.Models;
using HouseRentingSystem.Web.Models.Home;
using HouseRentingSystem.Services.Houses;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

using static HouseRentingSystem.Web.Areas.Admin.AdminConstants;

namespace HouseRentingSystem.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHouseService houses;
        public HomeController(IHouseService houses)
            => this.houses = houses;

        public IActionResult Index()
        {
            if (this.User.IsInRole(AdminRoleName))
            {
                return RedirectToAction("Index", "Home", new { area = "Admin" });
            }
            
            var houses = this.houses.LastThreeHouses();
            return View(houses);
        }

        public IActionResult Error(int statusCode)
        {
            if (statusCode == 400)
            {
                return View("Error400");
            }

            if (statusCode == 401)
            {
                return View("Error401");
            }

            return View();
        }
    }
}

DevOps for Developers/Software Engineering and DevOps - Sep 2024/08. Exams/SEDO-Regular-Exam-2024-10/HouseRentingSystem.Web/Views/Home/Error400.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <br>
        <div class="row">
            <div class="col-10">
                <img src="https://www.publicdomainpictures.net/pictures/280000/velka/not-found-image-15383864787lu.jpg" alt="Alternative image" class="img-thumbnail">
                <div class="text-left h4">
                    <p>Oops, better check that URL. Page was not found.</p>
                </div>
                <div class="text-left h4">  Go back to <a asp-controller="Home" asp-action="Index">Home</a> Page</div>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>

DevOps for Developers/Software Engineering and DevOps - Sep 2024/08. Exams/SEDO-Regular-Exam-2024-10/HouseRentingSystem.Web/Views/Home/Index.cshtml
@model IEnumerable<HouseIndexServiceModel>
@inject IAgentService agents
@{
    ViewData["Title"] = "Home Page";
    var houses = Model.ToList();
}

@if (!houses.Any())
{
    <div class="mt-4 p-5 bg-light">
        <h1 class="display-4">Welcome to the best place for renting houses!</h1>
        <p class="lead">
            There are no houses in the system currently available
            so why don't you just add one?
        </p>
        <hr class="my-4">
        <p class="lead">
            @if (this.User.Identity.IsAuthenticated
           && this.agents.ExistsById(this.User.Id()))
            {
                <a asp-controller="Houses" asp-action="Add"
           class="btn btn-primary btn-lg"
           role="button">Add House</a>
            }
        </p>
    </div>
}

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @for (int i = 0; i < houses.Count(); i++)
        {
            var house = houses[i];
            <div class="carousel-item @(i == 0 ? "active" : string.Empty)">
                <img class="d-block w-100" style="height:500px"
                 src="@house.ImageUrl" alt="@house.Title">
                <div class="carousel-caption d-none d-md-block">
                    <h5>
                        <a class="btn btn-primary" asp-controller="Houses" asp-action="Details"
                       asp-route-id="@house.Id"
                       asp-route-information="@house.GetInformation()"> @house.Title</a>
                    </h5>
                </div>
            </div>
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="mb-5"></div>

<div class="row">
    <div class="col-12 text-center">
        <button class="btn btn-primary" id="statistics-button">Show Statistics</button>
    </div>
</div>

<div class="mt-4 p-5 bg-light d-none" id="statistics">
    <div class="row">
        <h2 class="col-md-6 text-center" id="total-houses"></h2>
        <h2 class="col-md-6 text-center" id="total-rents"></h2>
    </div>
</div>

@section Scripts {
    <script>
        $('#statistics-button').on('click', ev => {
            $.get('/api/statistics', (data) => {
                $('#total-houses').text(data.totalHouses + " Houses");
                $('#total-rents').text(data.totalRents + " Rents");
                $('#statistics').removeClass('d-none');
                $('#statistics-button').hide();
            });
        });
    </script>
}